version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce      
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build docker images
          command: |
            docker version
            docker images
            docker build -t meetjs .
            docker images
            docker tag meetjs:latest 861611597471.dkr.ecr.us-west-2.amazonaws.com/meetjs:latest
            docker push 861611597471.dkr.ecr.us-west-2.amazonaws.com/meetjs:latest
      - deploy:
          name: Push application Docker image
          command: |
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              login="$(aws ecr get-login)"
              ${login}
              docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
            fi