version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
      
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.11.76

      - run: docker build -t meetjs:latest .
